from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

from base.models import BaseModel
from base.fields import ChoicesField
from base.choices import CurrentAffairCategory
from .choices import DigestType

# Create your models here.

class CurrentAffair(BaseModel):
    date = models.DateField()
    category = ChoicesField(CurrentAffairCategory)
    title = models.CharField(max_length=255)
    summary = models.TextField()
    source = models.CharField(max_length=100, blank=True, null=True)
    potential_questions = models.JSONField(blank=True, null=True, help_text="UPSC-style fact or mains-style question")
    tags = models.JSONField(default=list, blank=True)
    ai_insights = models.TextField(null=True, blank=True)
    usage_hint = models.TextField(null=True, blank=True)
    importance = models.IntegerField(
        null=True, blank=True, 
        validators=[MinValueValidator(1), MaxValueValidator(5)])
    article_link = models.URLField(null=True, blank=True)

    def __str__(self):
        return f"{self.date} - {self.title}"

    class Meta:
        ordering = ['-date', '-created_at']
        verbose_name = 'Current Affair'
        verbose_name_plural = 'Current Affairs'


class CurrentAffairsDigest(BaseModel):
    """
    Model to store compiled current affairs digests generated by Celery tasks.
    These can be daily summaries, weekly compilations, or custom digests.
    """
    title = models.CharField(max_length=255, help_text="Title of the digest")
    content = models.JSONField(help_text="Digest content including articles and metadata")
    date_generated = models.DateTimeField(default=timezone.now, help_text="When this digest was generated")
    digest_type = ChoicesField(DigestType, default=DigestType.DAILY, help_text="Type of digest")
    is_published = models.BooleanField(default=True, help_text="Whether this digest is published")
    articles_count = models.IntegerField(default=0, help_text="Number of articles in this digest")
    
    def __str__(self):
        return f"{self.digest_type.title()} - {self.title}"
    
    def save(self, *args, **kwargs):
        # Auto-calculate articles count from content
        if self.content and isinstance(self.content, dict):
            if 'articles_saved' in self.content:
                self.articles_count = self.content['articles_saved']
            elif 'saved_articles' in self.content:
                self.articles_count = len(self.content['saved_articles'])
            elif 'daily_digests' in self.content:
                # For weekly digests
                total = 0
                for daily in self.content['daily_digests']:
                    if isinstance(daily.get('content'), dict):
                        total += daily['content'].get('articles_saved', 0)
                self.articles_count = total
        
        super().save(*args, **kwargs)
    
    class Meta:
        ordering = ['-date_generated', '-created_at']
        verbose_name = 'Current Affairs Digest'
        verbose_name_plural = 'Current Affairs Digests'
        indexes = [
            models.Index(fields=['digest_type', 'date_generated']),
            models.Index(fields=['is_published', 'date_generated']),
        ]
