# Generated by Django 5.2 on 2025-05-22 19:20

import base.choices
import base.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAffair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('category', base.fields.ChoicesField(choices=[('Polity', 'POLITY'), ('Economy', 'ECONOMY'), ('International Relations', 'INTERNATIONAL_RELATIONS'), ('Environment', 'ENVIRONMENT'), ('Science & Technology', 'SCIENCE_TECHNOLOGY'), ('Social Issues', 'SOCIAL_ISSUES'), ('Security', 'SECURITY'), ('Miscellaneous', 'MISCELLANEOUS')], enum_class=base.choices.CurrentAffairCategory, max_length=23)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('potential_questions', models.JSONField(blank=True, help_text='UPSC-style fact or mains-style question', null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('ai_insights', models.TextField(blank=True, null=True)),
                ('usage_hint', models.TextField(blank=True, null=True)),
                ('importance', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('article_link', models.URLField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Current Affair',
                'verbose_name_plural': 'Current Affairs',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
