# Generated by Django 5.2 on 2025-05-05 18:44

import base.choices
import base.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_affairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaffair',
            name='ai_insight',
            field=models.TextField(blank=True, help_text='UPSC-style fact or mains-style question', null=True),
        ),
        migrations.AddField(
            model_name='currentaffair',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currentaffair',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='currentaffair',
            name='category',
            field=base.fields.ChoicesField(choices=[('Polity', 'POLITY'), ('Economy', 'ECONOMY'), ('International Relations', 'INTERNATIONAL_RELATIONS'), ('Environment', 'ENVIRONMENT'), ('Science & Technology', 'SCIENCE_TECHNOLOGY'), ('Social Issues', 'SOCIAL_ISSUES'), ('Security', 'SECURITY'), ('Miscellaneous', 'MISCELLANEOUS')], enum_class=base.choices.CurrentAffairCategory, max_length=23),
        ),
    ]
