# Generated by Django 5.2 on 2025-05-27 18:19

import base.fields
import current_affairs.choices
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_affairs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAffairsDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the digest', max_length=255)),
                ('content', models.JSONField(help_text='Digest content including articles and metadata')),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now, help_text='When this digest was generated')),
                ('digest_type', base.fields.ChoicesField(choices=[('daily', 'DAILY'), ('weekly', 'WEEKLY'), ('monthly', 'MONTHLY'), ('custom', 'CUSTOM')], default=current_affairs.choices.DigestType['DAILY'], enum_class=current_affairs.choices.DigestType, help_text='Type of digest', max_length=7)),
                ('is_published', models.BooleanField(default=True, help_text='Whether this digest is published')),
                ('articles_count', models.IntegerField(default=0, help_text='Number of articles in this digest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Current Affairs Digest',
                'verbose_name_plural': 'Current Affairs Digests',
                'ordering': ['-date_generated', '-created_at'],
                'indexes': [models.Index(fields=['digest_type', 'date_generated'], name='current_aff_digest__5a655e_idx'), models.Index(fields=['is_published', 'date_generated'], name='current_aff_is_publ_c99e48_idx')],
            },
        ),
    ]
