# Generated by Django 5.2 on 2025-05-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_affairs', '0002_currentaffair_ai_insight_currentaffair_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentaffair',
            old_name='key_concepts',
            new_name='ai_insights',
        ),
        migrations.RemoveField(
            model_name='currentaffair',
            name='ai_insight',
        ),
        migrations.AddField(
            model_name='currentaffair',
            name='potential_questions',
            field=models.JSONField(blank=True, help_text='UPSC-style fact or mains-style question', null=True),
        ),
    ]
