# Generated by Django 5.2 on 2025-05-14 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_affairs', '0003_rename_key_concepts_currentaffair_ai_insights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentaffair',
            name='article_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currentaffair',
            name='importance',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
