# Generated by Django 5.2 on 2025-04-19 06:47

import base.fields
import django.db.models.deletion
import upsc.choices
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=base.fields.ChoicesField(choices=[('multiple_choice', 'MULTIPLE_CHOICE'), ('short_answer', 'SHORT_ANSWER'), ('long_answer', 'LONG_ANSWER'), ('true_false', 'TRUE_FALSE'), ('matching', 'MATCHING')], default=upsc.choices.QuestionType['MULTIPLE_CHOICE'], enum_class=upsc.choices.QuestionType, max_length=15),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=base.fields.ChoicesField(choices=[('general_studies', 'GENERAL_STUDIES'), ('optional', 'OPTIONAL'), ('ethics', 'ETHICS'), ('essay', 'ESSAY'), ('current_affairs', 'CURRENT_AFFAIRS')], default=upsc.choices.SubjectCategory['GENERAL_STUDIES'], enum_class=upsc.choices.SubjectCategory, max_length=15),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty_level',
            field=base.fields.ChoicesField(choices=[('easy', 'EASY'), ('medium', 'MEDIUM'), ('hard', 'HARD'), ('expert', 'EXPERT')], default=upsc.choices.DifficultyLevel['MEDIUM'], enum_class=upsc.choices.DifficultyLevel, max_length=6),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
