# Generated by Django 5.2 on 2025-05-27 18:46

import base.choices
import base.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('api_type', base.fields.ChoicesField(choices=[('gemini', 'GEMINI'), ('openai', 'OPENAI'), ('claude', 'CLAUDE'), ('other', 'OTHER')], default=base.choices.APIType['GEMINI'], enum_class=base.choices.APIType, max_length=6)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('input_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('output_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('duration', models.FloatField(help_text='Request duration in seconds')),
                ('api_calls', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'base_token_usage',
                'ordering': ['-created_at'],
            },
        ),
    ]
